# Generated by Django 4.2.13 on 2026-06-30 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(max_length=100)),
                ('acting_context', models.CharField(help_text='subscriber | workspace_admin | platform_operator', max_length=50)),
                ('object_type', models.CharField(max_length=50)),
                ('object_id', models.BigIntegerField()),
                ('amount', models.IntegerField(help_text='Positive for grants, negative for consumption and expiry.')),
                ('previous_balance', models.IntegerField()),
                ('resulting_balance', models.IntegerField()),
                ('reason_code', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('acting_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_actions', to=settings.AUTH_USER_MODEL)),
                ('subject_user', models.ForeignKey(help_text='The user whose balance is affected by this entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ledger_entries',
                'indexes': [models.Index(fields=['subject_user', 'timestamp'], name='ledger_entr_subject_62cc69_idx'), models.Index(fields=['object_type', 'object_id'], name='ledger_entr_object__5f4a83_idx'), models.Index(fields=['acting_user', 'timestamp'], name='ledger_entr_acting__468107_idx'), models.Index(fields=['entry_type', 'timestamp'], name='ledger_entr_entry_t_809bb5_idx')],
            },
        ),
    ]
