# Generated by Django 4.2.13 on 2026-06-30 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
        migrations.CreateModel(
            name='CreditGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('subscription', 'Platform Subscription'), ('topup', 'Workspace Top-Up')], max_length=20)),
                ('amount', models.PositiveIntegerField(help_text='Number of credits granted in this allocation.')),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'credit_grants',
            },
        ),
        migrations.CreateModel(
            name='ScopedRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('administrator', 'Administrator'), ('viewer', 'Viewer')], max_length=20)),
                ('scope_object_type', models.CharField(max_length=50)),
                ('scope_object_id', models.BigIntegerField()),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'scoped_roles',
            },
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workspaces',
            },
        ),
        migrations.CreateModel(
            name='WorkspaceMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.workspace')),
            ],
            options={
                'db_table': 'workspace_memberships',
            },
        ),
        migrations.AddIndex(
            model_name='workspace',
            index=models.Index(fields=['slug'], name='workspaces_slug_cac896_idx'),
        ),
        migrations.AddField(
            model_name='scopedrole',
            name='granted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scopedrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scopedrole',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoped_roles', to='accounts.workspace'),
        ),
        migrations.AddField(
            model_name='creditgrant',
            name='revoked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditgrant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_grants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='creditgrant',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='If topup, which workspace issued this. Null = platform subscription.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_grants', to='accounts.workspace'),
        ),
        migrations.AddIndex(
            model_name='useraccount',
            index=models.Index(fields=['email'], name='user_accoun_email_2a098d_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['user', 'status'], name='workspace_m_user_id_de9200_idx'),
        ),
        migrations.AddIndex(
            model_name='workspacemembership',
            index=models.Index(fields=['workspace', 'status'], name='workspace_m_workspa_ce57d5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workspacemembership',
            unique_together={('user', 'workspace')},
        ),
        migrations.AddIndex(
            model_name='scopedrole',
            index=models.Index(fields=['user', 'scope_object_type', 'scope_object_id'], name='scoped_role_user_id_aa9732_idx'),
        ),
        migrations.AddIndex(
            model_name='scopedrole',
            index=models.Index(fields=['workspace', 'role_type', 'is_active'], name='scoped_role_workspa_aa6e02_idx'),
        ),
        migrations.AddIndex(
            model_name='creditgrant',
            index=models.Index(fields=['user', 'is_active'], name='credit_gran_user_id_cec4c9_idx'),
        ),
        migrations.AddIndex(
            model_name='creditgrant',
            index=models.Index(fields=['workspace', 'is_active'], name='credit_gran_workspa_f5a987_idx'),
        ),
        migrations.AddIndex(
            model_name='creditgrant',
            index=models.Index(fields=['expires_at'], name='credit_gran_expires_eb13de_idx'),
        ),
    ]
