# Generated by Django 4.2.13 on 2026-06-30 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('credit_cost', models.PositiveIntegerField(help_text='Number of credits deducted per booking against this plan.')),
                ('visibility', models.CharField(choices=[('open', 'Open'), ('workspace_only', 'Workspace Only')], default='open', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Maximum number of active bookings. Null = unlimited.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.workspace')),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('reversed', 'Reversed')], default='confirmed', max_length=20)),
                ('credits_consumed', models.PositiveIntegerField(help_text='Credits deducted at the time of booking. Snapshot of plan.credit_cost at booking time.')),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='credits.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['visibility', 'status'], name='plan_visibility_status_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['workspace', 'status'], name='plan_workspace_status_idx'),
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['category'], name='plan_category_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['plan', 'status'], name='booking_plan_status_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='booking_user_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('plan', 'user')},
        ),
    ]
